Double run

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,22 +17,28 @@ jobs:
       - name: Build
         run: go build -v ./...
 
-      - name: Test
-        id: test
-        run: |
-          status=0
-          test2json=''"$(go test ./... -json)"'' || status=1
-          
-          echo 'TEST2JSON<<EOF' >> $GITHUB_ENV
-          echo ''"$test2json"'' >> $GITHUB_ENV
-          echo 'EOF' >> $GITHUB_ENV
+      - name: Test tests1
+        run: set -o pipefail && go test ./tests1 -json | go run ./test_parser.go >> $GITHUB_STEP_SUMMARY
 
-          echo '${{ env.TEST2JSON }}'
+      - name: Test tests2
+        run: set -o pipefail && go test ./tests2 -json | go run ./test_parser.go >> $GITHUB_STEP_SUMMARY
 
-          [ $status -eq 0 ] && echo "passed" || echo "failed" ; exit 1
-
-      - name: Summary
-        if: always()
-        run: |
-          echo '${{ env.TEST2JSON }}' | go run ./test_parser.go >> $GITHUB_STEP_SUMMARY
-          echo $GITHUB_STEP_SUMMARY
+#      - name: Test
+#        id: test
+#        run: |
+#          status=0
+#          test2json=''"$(go test ./... -json)"'' || status=1
+#
+#          echo 'TEST2JSON<<EOF' >> $GITHUB_ENV
+#          echo ''"$test2json"'' >> $GITHUB_ENV
+#          echo 'EOF' >> $GITHUB_ENV
+#
+#          echo '${{ env.TEST2JSON }}'
+#
+#          [ $status -eq 0 ] && echo "passed" || echo "failed" ; exit 1
+#
+#      - name: Summary
+#        if: always()
+#        run: |
+#          echo '${{ env.TEST2JSON }}' | go run ./test_parser.go >> $GITHUB_STEP_SUMMARY
+#          echo $GITHUB_STEP_SUMMARY
