test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -23,14 +23,11 @@ jobs:
           echo "before test"
           status=0
           json=$(go test ./... -json) || status=1
-          echo "after test"
-          echo $status
-          [ $status -eq 0 ] && echo "command was successful" || echo "failed"
-          echo $json
           echo "::set-output name=test2json::$json"
+          [ $status -eq 0 ] && echo "passed" || echo "failed" ; exit 1
 
       - name: Summary
         if: always()
         run: |
-          echo "${{ steps.test.outputs.test2json }}" | go run ./test_parser.go >> $GITHUB_STEP_SUMMARY
+          printf '%s\n' "${{ steps.test.outputs.test2json }}" | go run ./test_parser.go >> $GITHUB_STEP_SUMMARY
           echo $GITHUB_STEP_SUMMARY
