try it

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,12 +25,20 @@ jobs:
       - name: Test tests1
         run: |
           touch tests1.out
-          go test ./tests1 -json > tests1.out || true
-          echo "catty"
-          cat ./tests1.out
-          echo "echoy"
-          echo "$(cat ./tests1.out)"
-          cat ./tests1.out | go run ./test_parser.go >> $GITHUB_STEP_SUMMARY
+          
+          ERROR=$(go test ./tests1 -json > tests1.out 2>&1)
+          echo "ERROR is..."
+          echo $ERROR
+          echo "ERROR is..."
+          
+          if [[ "$ERROR" != "" ]] exit 1 
+          
+          #go test ./tests1 -json > tests1.out || true
+          #echo "catty"
+          #cat ./tests1.out
+          #echo "echoy"
+          #echo "$(cat ./tests1.out)"
+          #cat ./tests1.out | go run ./test_parser.go >> $GITHUB_STEP_SUMMARY
 
   two-steps:
     runs-on: ubuntu-latest
